### ISSUE TITLE
Bug with registering user feeds

### ISSUE THREAD

**Issue by phillipcai** [Amelia-chan/Amelia#21]
Registering a user feed does not work.

Steps to reproduce:
1. Use the /register user command (with the appropriate name and channel tags filled in)
2. Receive a "The application did not respond" error message.

I should expect to choose what user I'm registering, and then to confirm, and then have Amelia-chan subscribe to that feed.

![image](https://user-images.githubusercontent.com/9725166/188784390-fd46647b-046a-4080-a91c-735154d794b3.png)
![image](https://user-images.githubusercontent.com/9725166/188784424-aa1d6822-5df6-4361-90e2-e9bb0a53fc5a.png)

The last time I successfully used the /register user command was August 9th, and I first noticed the issue on August 30th after Amelia-chan sent out the announcement that user feeds weren't supported anymore.

**Comment by ShindouMihou** [comment]
Thanks for reporting this issue, I have found the issue and will get to fixing it in a bit. Apologies for the delayed response since I was at class 👋

**Comment by ShindouMihou** [comment]
It took longer than expected due to some relevant issues from the Discord library that Amelia is using, but this issue should be closed now (I tested it just now) and also added some relevant privacy-changes (e.g. /subscribe /unsubscribe previously leaking reading list URLs).

Thanks for reporting this issue! ❤️

**Comment by phillipcai** [comment]
Thank you for fixing it so fast!

**Comment by phillipcai** [comment]
I think it's happened again? I tried to use /register user again yesterday, which last worked fine for me on November 30th, and I got the same issue.

**Comment by ShindouMihou** [comment]
> I think it's happened again? I tried to use /register user again yesterday, which last worked fine for me on November 30th, and I got the same issue.

Hello, there have been recent changes to ScribbleHub that somehow cause some blockades. I'll try and see what I can do before contacting Tony to see the most appropriate solution. 👏

**Comment by ShindouMihou** [comment]
> I think it's happened again? I tried to use /register user again yesterday, which last worked fine for me on November 30th, and I got the same issue.

Hello, this issue should now be resolved. I have contacted Tony and had the bot whitelisted. How about trying the command again?

**Comment by phillipcai** [comment]
Its fixed for me, thank you!
