### ISSUE TITLE
Update inversion: Amelia send updates in rss order instead of date order

### ISSUE THREAD

**Issue by Naheulf** [Amelia-chan/Amelia#25]
### Steps to Reproduce the Issue

1. Register a feed (reading list or author) to the bot
2. Add two new chapters in a row for one story in the list (
Note : Can't reproduce with the /test command as it only show the the latest chapter

### Expected Behavior
Amelia should send all chapter updates in the date sort order. I a story got a new chapter at 10h02 and another one at 10h05. Amelia should send the first chapter first and the second one later.

### Actual Behavior
Amelia send chapters in the rss order. So Amelia send a message for the 10h05 chapter first and send a message for the 10h02 one later. This result to a chapter inversion in discord.

### Debug Information
Extract from the RSS feed
```xml
...
				</item><item>
					<title>Rebirth of the Nephilim: Chapter 86: Unknown Intentions</title>
					<description>N/A</description>
					<link>https://www.scribblehub.com/read/664073-rebirth-of-the-nephilim/chapter/784126/</link>
					<category>Rebirth of the Nephilim</category>
					<category>664073</category>
				<pubDate>Sat, 17 Jun 2023 00:56:16 +0000</pubDate>
				</item><item>
					<title>Rebirth of the Nephilim: Chapter 85: Get Me Your Manager</title>
					<description>N/A</description>
					<link>https://www.scribblehub.com/read/664073-rebirth-of-the-nephilim/chapter/784125/</link>
					<category>Rebirth of the Nephilim</category>
					<category>664073</category>
				<pubDate>Sat, 17 Jun 2023 00:54:55 +0000</pubDate>
				</item><item>
...
``` 
How Amelia send it in discord:
![image](https://github.com/Amelia-chan/Amelia/assets/14990967/585ec26b-4b9f-4960-9740-d57c92594eb5)

Note: In that issue I don't care about the message format. Only the message order.

**Comment by ShindouMihou** [comment]
Amelia should now be sending feeds in ascending order.
