### ISSUE TITLE
Mesage Format: Too many spaces above @pings may lead to confusion.

### ISSUE THREAD

**Issue by Naheulf** [Amelia-chan/Amelia#26]
### Description of the Issue
There is too many blank lines between the "normal" message part and the list of @pings

### Steps to Reproduce the Issue
1. Register a feed in Amelia
2. Set at least one subscribe ping to that feed
3a. Wait for the feed to have at least two updates in less that 10minutes.
OR
3b. Spam the /test command to make amelia send few chapter update message in a row. You must do that from a different discord channel so the message won't interleaves

### Expected Behavior

@notifications should be closer to the related message than to the next message

### Actual Behavior

![image](https://github.com/Amelia-chan/Amelia/assets/14990967/585ec26b-4b9f-4960-9740-d57c92594eb5)
Look how the first @ping look closer to the second message.

**Comment by ShindouMihou** [comment]
Fixed the doubly newlines.
