### ISSUE TITLE
Can't register readinglist without tricking the URL

### ISSUE THREAD

**Issue by Naheulf** [Amelia-chan/Amelia#28]
### Steps to Reproduce the Issue

1. Login to scribblehub
2. Go to https://www.scribblehub.com/reading-list
3. Clic on the gear button to open the list setting
4. In `Global Settings` make sure `Disable Public List` is UNchecked.
5. In `Local (...) Settings` Right-click on the blue/green RSS button and copy the RSS URL
You should get something like https://www.rssscribblehub.com/rssfeed.php?type=local&uid=77291&unq=61e9d37fb3c94&lid=8
6. Use Amelia's `/register` command to register the list.

### Expected Behavior

Amelia send the confirmation message:
![✅ I will try my best to send updates for the reading list (MAM) in ⁠mises-à-jour!](https://github.com/Amelia-chan/Amelia/assets/14990967/28f441ca-454e-4697-8ed3-3024f8126566)

### Actual Behavior

Amelia send this error:
![❌ The link provided doesn't meet the specifications for reading list feed, please read https://github.com/Amelia-chan/Amelia/discussions/19 for more information.](https://github.com/Amelia-chan/Amelia/assets/14990967/f5f59ee2-9f74-46d2-87e4-ba9bea361d99)
However if you replace the domain name `www.rssscribblehub.com` with `www.scribblehub.com` it works !

### Debug Information
I use the link in this repo to add the bot in my test discord server.
Fixed By #24.

**Comment by ShindouMihou** [comment]
Thanks for reporting, just finished some schoolwork (thesis) and should be able to deploy the fix you issued later once I'm hope ❤️

**Comment by ShindouMihou** [comment]
Deployed this change to Amelia just now, if there is any more issues with this, feel free to say so.
