### ISSUE TITLE
No chapters update messages since 29 feb 2024 (2 days ago)

### ISSUE THREAD

**Issue by Naheulf** [Amelia-chan/Amelia#30]
### Description of the Issue

Amelia no lounger detect/send messages for new chapter in reading list.

### Steps to Reproduce the Issue

1. Publish or wait for a new chapter in a story present in a registered reading list
2. Wait 20 minutes

### Expected Behavior

Amelia should send a new message in Discord

### Actual Behavior

No message is send.

### Debug Information
The `/ping` command said scribblehub status a ok
> ScribbleHub Status
>🖋️ Author Feeds: ✅
>📖 Story Feeds: Unsupported ([Statement from Tony](https://forum.scribblehub.com/threads/cloudflare-blocking-rss-feeds.11117/post-243945))
>‼️ Inaccessible Feeds: 0 out of 100

The `/feeds` command still show the list as registered. However the `Last Update:` is outdated

**Comment by ShindouMihou** [comment]
In relation to the other issue that you made, this seems to be related to a newer server migration that was done on my servers to mitigate load across many different services which included Amelia being off-loaded to another server, which I had forgotten wasn't whitelisted by Tony.

I'll quickly spin up Amelia on the original server again and see how this goes.

**Comment by ShindouMihou** [comment]
Together with #31, Amelia should now be running on the previous server which should've fixed the issue. Although chapter updates for story feeds, if you have, are not going to be fixed but I think most of us already know that since it's been long removed.

Feel free to notify me if it isn't functioning on your end!

**Comment by Naheulf** [comment]
I can confirm I works. Thanks.
